Add feature flag in CONFIG_DB to decide whether TSA on supervisor updates the chassis-app-db or calls rexec to linecards (#27145)
* Add feature flag in CONFIG_DB to decide whether TSA on supervisor updates the chassis-app-db or calls rexec to linecards

Signed-off-by: saksarav <sakthivadivu.saravanaraj@nokia.com>

* Address the review comments

Signed-off-by: saksarav <sakthivadivu.saravanaraj@nokia.com>

* Fixed the review comment

Signed-off-by: saksarav <sakthivadivu.saravanaraj@nokia.com>

---------

Signed-off-by: saksarav <sakthivadivu.saravanaraj@nokia.com>

diff --git a/files/build_templates/docker_image_ctl.j2 b/files/build_templates/docker_image_ctl.j2
--- a/files/build_templates/docker_image_ctl.j2
+++ b/files/build_templates/docker_image_ctl.j2
@@ -343,14 +343,17 @@ function postStartAction()
             fi
         fi
 
-        # In SUP, enforce CHASSIS_APP_DB.tsa_enabled to be in sync with BGP_DEVICE_GLOBAL.STATE.tsa_enabled
+        # In SUP, enforce CHASSIS_APP_DB.tsa_enabled to be in sync with BGP_DEVICE_GLOBAL.STATE.tsa_enabled when chassis TSA uses CHASSIS_APP_DB
         if [[ -z "$DEV" ]] && [[ -f /etc/sonic/chassisdb.conf ]] && [[ $disaggregated_chassis -ne 1 ]]; then
-           tsa_cfg="$($SONIC_DB_CLI CONFIG_DB HGET "BGP_DEVICE_GLOBAL|STATE" "tsa_enabled")"
-           if [[ -n "$tsa_cfg" ]]; then
-              docker exec -i ${DOCKERNAME} $SONIC_DB_CLI CHASSIS_APP_DB HMSET "BGP_DEVICE_GLOBAL|STATE" tsa_enabled ${tsa_cfg}
-              OP_CODE=$?
-              if [ $OP_CODE -ne 0 ]; then
-                echo "Err: Cmd failed (exit code $OP_CODE). CHASSIS_APP_DB and CONFIG_DB may be incosistent wrt tsa_enabled"
+           chassis_tsa_supported_cfg="$($SONIC_DB_CLI CONFIG_DB HGET "BGP_DEVICE_GLOBAL|STATE" "chassis_tsa_supported")"
+           if [[ "$chassis_tsa_supported_cfg" == "true" ]]; then
+              tsa_cfg="$($SONIC_DB_CLI CONFIG_DB HGET "BGP_DEVICE_GLOBAL|STATE" "tsa_enabled")"
+              if [[ -n "$tsa_cfg" ]]; then
+                 docker exec -i ${DOCKERNAME} $SONIC_DB_CLI CHASSIS_APP_DB HMSET "BGP_DEVICE_GLOBAL|STATE" tsa_enabled ${tsa_cfg}
+                 OP_CODE=$?
+                 if [ $OP_CODE -ne 0 ]; then
+                   echo "Err: Cmd failed (exit code $OP_CODE). CHASSIS_APP_DB and CONFIG_DB may be incosistent wrt tsa_enabled"
+                 fi
               fi
            fi
         fi
